name: generate-snake-game

on:
  schedule:
    - cron: "0 */6 * * *"  # Run automatically every 6 hours
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Run on every push to the main branch

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: myselfshivams
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Set up Git
        run: |
          git config --global user.name "myselfshivams"
          git config --global user.email "30shivam09@gmail.com"

      - name: Commit and push changes
        run: |
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
          git commit -m "Update contribution grid snake" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
